name: Deploy # 名称
on: # 什么时候执行这个workflow
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs: # 一些列的jobs
  deploy: # job_id
    runs-on: ubuntu-latest # 运行环境
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps: # deploy这个job对应的一系列运行步骤
      - uses: actions/checkout@v4 # 使用官方提供的action, 拉取代码
        name: checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4 # 官方action，安装node
        name: install node.js
        with:
          node-version: 16
          cache: npm
      - uses: pnpm/action-setup@v2 # 使用pnpm官方提供的action，安装pnpm
        name: Install pnpm
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory # 手动写脚本，获取store_path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4 # 官方action，用于缓存依赖
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies # 手动写脚本，安装依赖
        run: pnpm install
      - name: Build # 手动写脚本，执行构建命令
        run: pnpm build
      - uses: actions/configure-pages@v5 # 官方action
      - uses: actions/upload-pages-artifact@v3 # 官方action，上传文件
        with:
          path: docs/.vitepress/dist
      - name: Deploy # 官方action，部署到指定服务器
        id: deployment
        uses: actions/deploy-pages@v4
